config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  post 'create_booking/:safari_id/:id', to: 'pages#create_booking', as: 'create_booking'
  patch 'cancel_booking/:safari_id/:id', to: 'pages#cancel_booking', as: 'cancel_booking'
  patch 'accept_booking/:safari_id/:id', to: 'pages#accept_booking', as: 'accept_booking'

  resources :safaris do
    resources :reviews, only: [:create]
  end
  resources :users, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :safari
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking, dependent: :destroy
  belongs_to :safari, dependent: :destroy
end

app/models/safari.rb
class Safari < ApplicationRecord
  has_many :safari_images
  has_many :bookings
  has_many :reviews
  belongs_to :user
  geocoded_by :address
  accepts_nested_attributes_for :safari_images
  after_validation :geocode, if: :address_changed?


  def has_been_booked?(user)
    self.bookings.include? user.bookings.where(safari: self).first
  end
end

app/models/safari_image.rb
class SafariImage < ApplicationRecord
  belongs_to :safari
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :created_safaris, class_name: "Safari", foreign_key: :user_id
  has_many :booked_safaris, through: :bookings, source: :safari
  mount_uploader :avatar, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @any_bookings = any_bookings?
    if user_signed_in?
      @user = current_user
      @user_bookings = @user.bookings
    else
      redirect_to :safaris
    end
  end

  def create_booking
    @booking = Booking.new
    @safari = Safari.find(params[:safari_id])
    @user = User.find(params[:id])
    @booking.safari = @safari
    @booking.user = @user
    if @booking.save
      redirect_to dashboard_path
    else
      redirect_to new_user_registration_path
    end
  end

  def cancel_booking
    @safari = Safari.find(params[:safari_id])
    @user = User.find(params[:id])
    @booking = Booking.where(safari_id: @safari.id, user_id: @user.id).first
    @booking.status = "decline"
    @booking.save
    redirect_to :dashboard
  end

  def accept_booking
    @safari = Safari.find(params[:safari_id])
    @user = User.find(params[:id])
    @booking = Booking.where(safari_id: @safari.id, user_id: @user.id).first
    @booking.status = "accept"
    @booking.save
    redirect_to :dashboard
  end

  def any_bookings?
    @array_of_saf_with_bookings = []
    current_user.created_safaris.each do |safari|
      if safari.bookings.where(status: "pending") != []
        @array_of_saf_with_bookings << safari
      end
    end
    @array_of_saf_with_bookings
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :avatar, :avatar_cache, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :avatar, :avatar_cache, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_safari, only: [:create]

  def create
    @review = Review.new(review_params)
    @review.safari = @safari
    @review.booking = current_user.bookings.where(safari: @safari).first
    if @review.save
      redirect_to safari_path(@safari)
    else
      render 'safaris/show'
    end
  end

  private

  def set_safari
    @safari = Safari.find(params[:safari_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/safaris_controller.rb
class SafarisController < ApplicationController
  before_action :set_safari, only: [:show]

  def index
    if params[:search].present?
      # @safaris = Safari.where('title LIKE ?', params[:search])
      @safaris = Safari.where("lower(title) LIKE ? OR lower(address) LIKE ?", "%#{params[:search].downcase}%", "%#{params[:search].downcase}%")
      if @safaris == []
        @safaris = Safari.where.not(latitude: nil, longitude: nil)
      end
    else
      @safaris = Safari.where.not(latitude: nil, longitude: nil)
    end
    @hash = Gmaps4rails.build_markers(@safaris) do |safari, marker|
      marker.lat safari.latitude
      marker.lng safari.longitude
      # marker.infowindow render_to_string(partial: "/safaris/map_box", locals: { safari: safari })
    end
  end

   def show
    @status = ""
    @review = Review.new
    @reviews = Review.all
    @safari = Safari.find(params[:id])
    @safari_coordinates = { lat: @safari.latitude, lng: @safari.longitude }
    @user = @safari.user
    if current_user
      @booking = Booking.where(safari_id: @safari.id, user_id: current_user.id).first
      if @booking
        if @booking.status == "accept"
          @status = @booking.status
        elsif @booking.status == "decline"
          @status = @booking.status
        else
          @status = @booking.status
        end
      end
    end
  end


  def new
    unless current_user
      redirect_to new_user_session_url
    end
    @safari = Safari.new
    @safari_images = @safari.safari_images.build
  end

  def create
    @safari = Safari.new(safari_params)
    @safari.user = current_user
    if @safari.save
      params[:safari_images]['photo'].each do |p|
        @safari.safari_images.create!(photo: p)
      end
      redirect_to safari_path(@safari)
    else
      render :new
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def safari_params
    params.require(:safari).permit(:title, :address, :price, :description, :capacity, :date, safari_images: [:id, :safari_id, :photo])
  end

  def set_safari
    @safari = Safari.find(params[:id])
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def show

  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "elephant.png"%> <p>SafariNow</p>
    <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Search -->
    <% unless current_page?(root_path) && !user_signed_in? %>
      <% if !current_page?(root_path) %>
        <%= form_tag safaris_path, method: :get do  %>
        <label class="search" for="inpt_search">
          <%= text_field_tag :search, nil, id: "inpt_search"%>
        </label>
      <% end %>
    <% end %>
    <%= link_to "Add a Safari", new_safari_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% else %>
       <%= link_to "Sign up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link navbar-sign-in" %>
    <% end %>

    <% if user_signed_in? %>
    <!-- Profile picture with dropdown list -->
     <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.avatar? %>
            <%= cl_image_tag current_user.avatar_url(:bright_face), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"  %>
          <% elsif !current_user.facebook_picture_url.nil? %>
            <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>Add safari</li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One|Muli:300,400,600|Source+Sans+Pro:300,400,600" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title><%= yield(:title_tag) || "Safari" %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag %>
  </head>
  <body>

    <%= render partial: 'layouts/navbar' %>
    <%= render "shared/flashes" %>
    <div class="wrapper">
    <% if devise_controller? %>
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-md-6 col-md-offset-3 devise-form">
            <%= yield %>
          </div>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
    </div>
    <%= yield(:before_js) %>
    <%= javascript_include_tag "application" %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-3 col-offeset-sm-1">
      <div class="profile-info">
        <% if @user.avatar? %>
            <%= cl_image_tag @user.avatar.url, class: "avatar-dashboard" %>
        <% elsif !@user.facebook_picture_url.nil? %>
          <%= image_tag @user.facebook_picture_url, class: "avatar-dashboard"  %>
        <% else %>
          <%= image_tag "http://placehold.it/200x200", class: "avatar-dashboard" %>
        <% end %>
        <div class="profile-links">
        <div class="edit-dashboard">
          <h2> <%= @user.first_name %> </h2>
          <%= link_to "Edit Profile", edit_user_registration_path %>
        </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-8">
      <div class="category-dashboard-current">
          <% unless @user_bookings == []  %>
        <h2 class="h2-bookings">Your bookings</h2>
        <div class="all-messages">
            <% @user_bookings.each do |booking| %>
              <div class="dashboard-messages">
                  <% if booking.safari.user.avatar? %>
                      <%= cl_image_tag booking.safari.user.avatar.url(:bright_face), class: "avatar-dashboard-booking" %>
                  <% elsif !booking.safari.user.facebook_picture_url.nil? %>
                    <%= image_tag booking.safari.user.facebook_picture_url, class: "avatar-dashboard-booking"  %>
                  <% else %>
                    <%= image_tag "http://placehold.it/30x30", class: "avatar-dashboard-booking" %>
                  <% end %>
                  <div class="user-name">
                    <h4> <%= booking.safari.user.first_name %> <%= booking.safari.user.last_name %> </h4>
                  </div>
                  <%# booking.safari.user.avatar %>
                  <%# booking.safari.user.first_name %>

                <div class="safari-message">
                  <%# booking.safari.title %>
                  <%= link_to safari_path(booking.safari) do %>
                    <h4> <%= booking.safari.title %> </h4>
                  <% end %>
                  <p> <%= truncate(booking.safari.description, :length => 80) %> </p>
                </div>
                <div class="booking-info">
                  <%# booking.status %>
                  <% if booking.status == "decline"  %>
                    <p style="color: red; opacity: 1"> <%= booking.status.capitalize %> </p>
                  <% elsif booking.status == "accept" %>
                    <p style="color: green; opacity: 1"> <%= booking.status.capitalize %> </p>
                  <% else %>
                    <p style="color: #C0C2C3"> <%= booking.status.capitalize %></p>
                  <% end %>
                </div>
              </div>
            <% end %>
           <% else %>
            <div class="empty-bookings">
              <div class="button-div">
              <h2> No bookings yet. </h2>
                <%= link_to "Explore new safaris", safaris_path, class: "button-dashboard" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
    <div class="category-dashboard-current">
        <% if @current_user.created_safaris != [] &&  @any_bookings != []  %>
        <h2 class="h2-bookings">Your guests</h2>
        <div class="all-messages">
             <% current_user.created_safaris.each do |safari| %>
                <% safari.bookings.where(status: "pending").each do |booking| %>
              <div class="dashboard-messages">
                  <% if booking.user.avatar? %>
                    <%= cl_image_tag booking.user.avatar, class: "avatar-dashboard-booking" %>
                  <% elsif !booking.user.facebook_picture_url.nil? %>
                    <%= image_tag booking.user.facebook_picture_url, class: "avatar-dashboard-booking" %>
                  <% else %>
                    <%= image_tag "http://placehold.it/50x50", class: "avatar-dashboard-booking" %>
                  <% end %>
                  <div class="user-name">
                    <h4> <%= booking.user.first_name %> <%= booking.user.last_name %> </h4>
                  </div>
                <div class="safari-message">
                  <h4> <%= booking.safari.title %> </h4>
                  <p> <%= truncate(booking.safari.description, :length => 80) %> </p>
                </div>
                <div class="booking-info-status">
                  <%= link_to accept_booking_path(booking.safari, booking.user), method: :patch do  %>
                    <p> <i class="fa fa-check green-tick" aria-hidden="true"></i> </p>
                  <% end %>
                  <%= link_to cancel_booking_path(booking.safari, booking.user), method: :patch do %>
                    <p> <i class="fa fa-times red-tick" aria-hidden="true"></i> </p>
                  <% end %>
                </div>
              </div>
              <% end %>
            <% end %>
         <% elsif @current_user.created_safaris == [] %>
          <div class="empty-bookings">
            <div class="button-div">
            <h2> Your didnt create any safaris </h2>
              <%= link_to "Create new safari", new_safari_path, class: "button-dashboard" %>
            </div>
          </div>
          <% else %>
            <div class="empty-bookings">
              <div class="button-div">
                <h2> Waiting for new guest </h2>
              </div>
            </div>
         <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for(:title_tag) do %>
  Safari Now
<% end %>

<div class="home">
  <div class="search-and-button">
  <h2 class="main-title">Explore safaris in</h2>
    <%= form_tag safaris_path, :method => 'get', enforce_utf8: false do %>
    <span id="typed-overlay">
      <%= text_field_tag :search, params[:search], id: "main-search" %>
      <div id="type">
        <span id="typed"></span>
      </div>
    </span>

      <%= button_tag(type: 'submit')  do %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    <% end %>
  </div>
</div>

<% content_for(:after_js) do %>

 <script>
   $(function(){
        $("#typed").typed({
          strings: ['South Africa', 'Botswana', 'Kenya', 'Mozambique', 'Namibia', 'Rwanda', 'South Africa', 'Tanzania', 'Uganda', 'Zambia', 'Zimbabwe'],
          typeSpeed: 110,
          backSpeed: 20,
          backDelay: 700,
          loop: true,
          smartBackspace: true,
        });
      });
 </script>

  <script>
    var typedOverlay = document.getElementById('typed-overlay');
    var search = document.getElementById('main-search');

    typedOverlay.addEventListener('mouseenter', hideTyped);
    search.addEventListener('focus', hideTyped);
    search.addEventListener('mouseleave', showTyped);

    function hideTyped() {
      search.focus();
      document.getElementById('type').style.display = "none";
    }
    function showTyped() {
      if (search.value === "") {
        search.blur();
        document.getElementById('type').style.display = "";}
    }
  </script>

<% end %>





app/views/safaris/new.html.erb
<div class="container">
  <div class="col-xs-12 col-md-6 col-md-offset-3">


  <%= simple_form_for @safari, html: { multipart: true } do |f| %>

    <div class="form-inputs devise-form">
      <h2>Add a new safari</h2>
      <%= f.input :title, required: true, autofocus: true %>
      <%= f.fields_for :safari_images do |p| %>
        <div class="field">
          <%= p.label :photo %><br>
          <%= p.file_field :photo, :multiple => true, name: "safari_images[photo][]" %>
        </div>
      <% end %>
      <%# f.input :photos_cache, as: :hidden %>
      <%= f.input :address, input_html: { class: 'address-search' } %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :capacity %>
      <%= f.input :date %>
    <div class="form-actions">
      <%= f.button :submit, "create" %>
    </div>

    </div>


  <% end %>
  </div>
</div>


<%= content_for(:before_js) do %>
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyChl4fydvT8OtNqTPp8fXIHg7avv0b2650"></script>
<% end %>

app/views/safaris/show.html.erb
<div class="show-banner-box">

<div class="swiper-container">
  <div class="swiper-wrapper">
  <!--   <%# if @safari.safari_images %> -->
     <% unless @safari.safari_images == [] %>
      <% @safari.safari_images.each do |images_instance| %>
        <div class="swiper-slide">
          <%= cl_image_tag images_instance.photo, class: "show-banner", crop: :fill %>
        </div>
      <% end %>
    <% else %>
      <div class="swiper-slide">
        <%= cl_image_tag "safari-default_ng7zub.jpg", class: "show-banner" %>
      </div>
    <% end %>
  </div>

  <% if (@safari.safari_images != []) || (@safari.safari_images.count == 1) %>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next swiper-button-white"></div>
    <div class="swiper-button-prev swiper-button-white"></div>
  <% end %>
</div>
</div>

  <div class="show-banner-content">
    <div class="summary">
      <h2><%= @safari.title %></h2>
    </div>
    <div class="book-and-avatar">
      <% if @user.avatar? %>
        <%= cl_image_tag @user.avatar_url(:bright_face), class: "safari-owner" %>
      <% elsif !@user.facebook_picture_url.nil? %>
        <%= image_tag @user.facebook_picture_url, class: "safari-owner" %>
      <% else %>
        <%= image_tag "http://placehold.it/50x50", class: "safari-owner" %>
      <% end %>
      <a class="safari-owner-link" href="#" ></a>
      <div id="book-button">
        <% if current_user == @safari.user %>
        <% elsif  @booking %>
          <%= link_to @status.capitalize, dashboard_path %>
        <% elsif current_user %>
          <%= link_to "Book now", create_booking_path(@safari, current_user), method: :post %>
        <% else %>
          <%= link_to "Book now", new_user_session_path %>
        <% end %>
      </div>
    </div>

  <div class="info">
    <h3><%= @safari.address %> - £<%= @safari.price %></h3>
    <div class="date">
      <p><%= @safari.date %></p>
    </div>
    <p><%= @safari.description %></p>
  </div>
  </div>

<div id="show-map" style="width: 100%; height: 400px;"></div>


<div class="container">

<!-- Button trigger modal -->
<div class="review text-center">
<% if current_user %>
  <% if @safari.has_been_booked?(current_user) %>

  <button type="button" class="text-center" id="review-button" data-toggle="modal" data-target="#myModal">
    Add a review
  </button>
  <% end %>
  <% end %>


<!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog dialog-show" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Add a review</h4>
        </div>
        <div class="modal-body">
          <%= render 'shared/show-form', review: @review, safari: @safari %>
        </div>
       <!--  <div class="modal-footer"> -->

          <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
        <!-- </div> -->
      </div>
    </div>
  </div>
</div>

  <div class="row">
    <% @reviews.each do |review| %>
      <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <div class="reviews">
          <%= review.booking.user.first_name %> -
          <%= review.content %>
          <% review.rating.times do %>
            <i class="fa fa-star"></i>
          <% end %>
          <% (5 - review.rating).times do %>
            <i class="fa fa-star-o"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>




<%= content_for(:before_js) do %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyCMtlyoljyulu4QGTB6SxcjUMxW-lCmv2I" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
<% end %>

<% content_for(:after_js) do %>

  <script>
    $(document).ready(function() {
      var styles = [
    {
        "featureType": "administrative",
        "elementType": "labels.text.fill",
        "stylers": [
            {
                "color": "#444444"
            }
        ]
    },
    {
        "featureType": "landscape",
        "elementType": "all",
        "stylers": [
            {
                "color": "#f2f2f2"
            }
        ]
    },
    {
        "featureType": "landscape.natural",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "on"
            },
            {
                "color": "#b4f06d"
            },
            {
                "saturation": "-40"
            },
            {
                "lightness": "58"
            }
        ]
    },
    {
        "featureType": "landscape.natural.landcover",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "landscape.natural.terrain",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.park",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "simplified"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "all",
        "stylers": [
            {
                "saturation": -100
            },
            {
                "lightness": 45
            },
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "labels.icon",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit",
        "elementType": "all",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "water",
        "elementType": "all",
        "stylers": [
            {
                "color": "#f4f2cd"
            },
            {
                "visibility": "on"
            }
        ]
    }
]
      var handler = Gmaps.build('Google');
      handler.buildMap({
        provider: {
        styles: styles },

        internal: { id: 'show-map' } }, function() {
        markers = handler.addMarkers([<%= raw @safari_coordinates.to_json %>]);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(6);
        }
      });
    });
  </script>

    <%= javascript_tag do %>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        slidesPerView: 1,
        paginationClickable: true,
        spaceBetween: 30,
        keyboardControl: true,
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
    });
  <% end %>

<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_show-form.html.erb
<%= simple_form_for [safari, review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, as: :select, collection: (1..5) %>
  <%= f.button :submit %>
<% end %>
<form action="/safaris" method="post"></form>